language: python
python:
- '2.7'
install:
- pip install nodeenv
- nodeenv -pn latest
- npm install
script:
- gatsby build
- tar cf pyconar.tar.gz public/
before_install:
- openssl aes-256-cbc -K $encrypted_2abef4340ecd_key -iv $encrypted_2abef4340ecd_iv
  -in deploy_rsa.enc -out deploy_rsa -d
