language: python

python:
  - "3.5"

# command to install dependencies
install:
  - pip install nodeenv
  - nodeenv -pn latest
  - npm install

script:
  - gatsby build
  - tar cf pyconar.tar.gz public/
