language: python

python:
- '2.7'

install:
- pip install nodeenv
- nodeenv -pn latest
- npm install

script:
- npm run build
- tar cf pyconar.tar.gz public/

addons:
  ssh_known_hosts: $DEPLOY_HOST

before_deploy:
- openssl aes-256-cbc -K $encrypted_2abef4340ecd_key -iv $encrypted_2abef4340ecd_iv
    -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/<dir> $SSH-USER@$DEPLOY_HOST:$DEPLOY_PATH
  on:
    branch: master
